name: Python CI

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8

    - name: Lint with flake8
      run: |
        flake8 . --count --exclude=./fastapi/lib/python3.11/site-packages --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --exclude=./fastapi/lib/python3.11/site-packages --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
